### PR TITLE
Created SECURITY.md

### PR DESCRIPTION
**Pull request by VanshajPoonia**
I have added a new file named SECURITY.md
This contribution is for hacktober fest 😄 
NOTE : Please change the email address according to the mail id of the company.

## Type of Pull Request 

-  📖 Documentation Update

### CODE REVIEW

**Comment by janhavi-ai** [comment]
Hey @VanshajPoonia please add "support@symbl.ai" as the contact email address!

**Comment by VanshajPoonia** [comment]
Should I add .com after the mail id like support@symbl.ai.com??

**Comment by janhavi-ai** [comment]
Nope, no dot com!

**Comment by VanshajPoonia** [comment]
I have opened a new pull request please check

**Pull request merged**
